services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PG_HOST=postgres_db
      - PG_PORT=5432
      - PG_USER=${POSTGRES_USER}
      - PG_PASS=${POSTGRES_PASSWORD}
      - PG_NAME=${POSTGRES_DB}
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_data: